[package]
name = "WebHound"
version = "0.1.0"
edition = "2024"

[dependencies]


[workspace]
members = [
  "crates/cli",
  "crates/core",
  "crates/scanner",
  "crates/analyzer",
  "crates/server",
  "crates/config",
]
resolver = "2"
