#!/usr/bin/env bash
set -euo pipefail

# make_env.sh
# Создаёт .env с:
#   export ORT_DYLIB_PATH=".../LibPy/libonnxruntime.so.X"
#   export LD_LIBRARY_PATH=".../LibPy:${LD_LIBRARY_PATH}"
#
# Ищет LibPy/libonnxruntime.so* автоматически (сначала вверх по дереву, затем find).

OUT_NAME=".env"

abspath() {
    # Linux: readlink -f обычно есть. Если нет — fallback на python.
    if command -v readlink >/dev/null 2>&1; then
        readlink -f "$1" 2>/dev/null || python3 -c 'import os,sys;print(os.path.abspath(sys.argv[1]))' "$1"
    else
        python3 -c 'import os,sys;print(os.path.abspath(sys.argv[1]))' "$1"
    fi
}

pick_best_lib() {
    local libdir="$1"
    # 1) если есть "libonnxruntime.so" (часто symlink) — берём его
    if [[ -f "${libdir}/libonnxruntime.so" ]]; then
        echo "${libdir}/libonnxruntime.so"
        return 0
    fi
    # 2) иначе берём самый "новый" по версии libonnxruntime.so.*
    local best
    best="$(ls -1 "${libdir}"/libonnxruntime.so.* 2>/dev/null | sort -V | tail -n 1 || true)"
    [[ -n "${best}" ]] && echo "${best}" && return 0
    return 1
}

find_repo_root_and_lib() {
    local start="$1"
    local d="$start"

    # Быстрый поиск вверх: проверяем варианты LibPy в текущей и родительских папках
    while [[ "$d" != "/" ]]; do
        if [[ -d "${d}/LibPy" ]]; then
            if lib="$(pick_best_lib "${d}/LibPy")"; then
                echo "${d}|${lib}"
                return 0
            fi
        fi
        if [[ -d "${d}/WebHound/LibPy" ]]; then
            if lib="$(pick_best_lib "${d}/WebHound/LibPy")"; then
                echo "${d}/WebHound|${lib}"
                return 0
            fi
        fi
        d="$(dirname "$d")"
    done

    # Fallback: find (может быть чуть медленнее, но универсально)
    local hit
    hit="$(find "$start" -maxdepth 6 -type f -name 'libonnxruntime.so*' 2>/dev/null | head -n 1 || true)"
    if [[ -n "$hit" ]]; then
        local libdir
        libdir="$(dirname "$hit")"
        local root
        root="$(dirname "$libdir")" # предполагаем .../<ROOT>/LibPy/<lib>
        echo "${root}|${hit}"
        return 0
    fi

    return 1
}

main() {
    local script_dir
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    local start_dir="${PWD}"

    # Можно явно указать корень через WEBHOUND_ROOT
    if [[ "${WEBHOUND_ROOT:-}" != "" ]]; then
        start_dir="$(abspath "$WEBHOUND_ROOT")"
    fi

    local found
    if ! found="$(find_repo_root_and_lib "$start_dir")"; then
        # попробуем от директории скрипта
        if ! found="$(find_repo_root_and_lib "$script_dir")"; then
            echo "❌ Не нашёл libonnxruntime.so* в LibPy."
            echo "   Запусти из корня проекта или задай WEBHOUND_ROOT=/path/to/WebHound"
            exit 1
        fi
    fi

    local repo_root="${found%%|*}"
    local lib_path="${found#*|}"
    local lib_abs repo_abs lib_dir_abs

    repo_abs="$(abspath "$repo_root")"
    lib_abs="$(abspath "$lib_path")"
    lib_dir_abs="$(abspath "$(dirname "$lib_abs")")"

    local out="${repo_abs}/${OUT_NAME}"

    cat >"$out" <<EOF
# Auto-generated by make_env.sh
export ORT_DYLIB_PATH="${lib_abs}"
export LD_LIBRARY_PATH="${lib_dir_abs}:\${LD_LIBRARY_PATH}"
EOF

    echo "✅ Создан: $out"
    echo "   ORT_DYLIB_PATH=$lib_abs"
    echo "   LD_LIBRARY_PATH добавит: $lib_dir_abs"
    echo ""
    echo "Использование:"
    echo "  source \"$out\""
}

main "$@"
