#!/usr/bin/env bash
set -euo pipefail

# make_env.sh
# Создаёт .env с:
#   export ORT_DYLIB_PATH=".../LibPy/libonnxruntime.so.X"
#   export LD_LIBRARY_PATH=".../LibPy:${LD_LIBRARY_PATH}"
#   export WEBHOUND_ROOT=".../WebHound"
#   export WEBHOUND_VISION_MODEL=".../assets/ml/eyeballer.onnx"
#   export WEBHOUND_TEXT_MODEL_DIR=".../assets/ml/text_secret_classifier"
#   export WEBHOUND_TEXT_MODEL=".../assets/ml/text_secret_classifier/model.onnx"
#   export WEBHOUND_TEXT_METADATA=".../assets/ml/text_secret_classifier/export_metadata.json"
#   export WEBHOUND_TEXT_TOKENIZER=".../assets/ml/text_secret_classifier/tokenizer/tokenizer.json"
#
# Ищет LibPy/libonnxruntime.so* автоматически (сначала вверх по дереву, затем find).

OUT_NAME=".env"

abspath() {
    if command -v readlink >/dev/null 2>&1; then
        readlink -f "$1" 2>/dev/null || python3 -c 'import os,sys;print(os.path.abspath(sys.argv[1]))' "$1"
    else
        python3 -c 'import os,sys;print(os.path.abspath(sys.argv[1]))' "$1"
    fi
}

pick_best_lib() {
    local libdir="$1"
    if [[ -f "${libdir}/libonnxruntime.so" ]]; then
        echo "${libdir}/libonnxruntime.so"
        return 0
    fi
    local best
    best="$(ls -1 "${libdir}"/libonnxruntime.so.* 2>/dev/null | sort -V | tail -n 1 || true)"
    [[ -n "${best}" ]] && echo "${best}" && return 0
    return 1
}

find_repo_root_and_lib() {
    local start="$1"
    local d="$start"

    while [[ "$d" != "/" ]]; do
        if [[ -d "${d}/LibPy" ]]; then
            if lib="$(pick_best_lib "${d}/LibPy")"; then
                echo "${d}|${lib}"
                return 0
            fi
        fi
        if [[ -d "${d}/WebHound/LibPy" ]]; then
            if lib="$(pick_best_lib "${d}/WebHound/LibPy")"; then
                echo "${d}/WebHound|${lib}"
                return 0
            fi
        fi
        d="$(dirname "$d")"
    done

    local hit
    hit="$(find "$start" -maxdepth 6 -type f -name 'libonnxruntime.so*' 2>/dev/null | head -n 1 || true)"
    if [[ -n "$hit" ]]; then
        local libdir
        libdir="$(dirname "$hit")"
        local root
        root="$(dirname "$libdir")"
        echo "${root}|${hit}"
        return 0
    fi

    return 1
}

resolve_if_exists() {
    local p="$1"
    if [[ -e "$p" ]]; then
        abspath "$p"
    fi
}

main() {
    local script_dir
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    local start_dir="${PWD}"

    if [[ "${WEBHOUND_ROOT:-}" != "" ]]; then
        start_dir="$(abspath "$WEBHOUND_ROOT")"
    fi

    local found
    if ! found="$(find_repo_root_and_lib "$start_dir")"; then
        if ! found="$(find_repo_root_and_lib "$script_dir")"; then
            echo "Не нашёл libonnxruntime.so* в LibPy."
            echo "Запусти из корня проекта или задай WEBHOUND_ROOT=/path/to/WebHound"
            exit 1
        fi
    fi

    local repo_root="${found%%|*}"
    local lib_path="${found#*|}"
    local lib_abs repo_abs lib_dir_abs

    repo_abs="$(abspath "$repo_root")"
    lib_abs="$(abspath "$lib_path")"
    lib_dir_abs="$(abspath "$(dirname "$lib_abs")")"

    local vision_model text_model_dir text_model text_metadata text_tokenizer

    vision_model="$(resolve_if_exists "${repo_abs}/src/asset/ml/eyehound_mobilenet.onnx" || true)"
    text_model_dir="$(resolve_if_exists "${repo_abs}/src/asset/ml/text_secret_classifier" || true)"
    text_model="$(resolve_if_exists "${repo_abs}/src/asset/ml/text_secret_classifier/model.onnx" || true)"
    text_metadata="$(resolve_if_exists "${repo_abs}/src/asset/ml/text_secret_classifier/export_metadata.json" || true)"
    text_tokenizer="$(resolve_if_exists "${repo_abs}/src/asset/ml/text_secret_classifier/tokenizer/tokenizer.json" || true)"

    local out="${repo_abs}/${OUT_NAME}"

    cat >"$out" <<EOF
# Auto-generated by make_env.sh
export WEBHOUND_ROOT="${repo_abs}"

export ORT_DYLIB_PATH="${lib_abs}"
export LD_LIBRARY_PATH="${lib_dir_abs}:\${LD_LIBRARY_PATH}"

EOF

    if [[ -n "${vision_model}" ]]; then
        cat >>"$out" <<EOF
export WEBHOUND_VISION_MODEL="${vision_model}"
EOF
    else
        cat >>"$out" <<'EOF'
# export WEBHOUND_VISION_MODEL="/path/to/WebHound/assets/ml/eyehound_mobilenet.onnx "
EOF
    fi

    if [[ -n "${text_model_dir}" ]]; then
        cat >>"$out" <<EOF
export WEBHOUND_TEXT_MODEL_DIR="${text_model_dir}"
EOF
    else
        cat >>"$out" <<'EOF'
# export WEBHOUND_TEXT_MODEL_DIR="/path/to/WebHound/assets/ml/text_secret_classifier"
EOF
    fi

    if [[ -n "${text_model}" ]]; then
        cat >>"$out" <<EOF
export WEBHOUND_TEXT_MODEL="${text_model}"
EOF
    else
        cat >>"$out" <<'EOF'
# export WEBHOUND_TEXT_MODEL="/path/to/WebHound/assets/ml/text_secret_classifier/model.onnx"
EOF
    fi

    if [[ -n "${text_metadata}" ]]; then
        cat >>"$out" <<EOF
export WEBHOUND_TEXT_METADATA="${text_metadata}"
EOF
    else
        cat >>"$out" <<'EOF'
# export WEBHOUND_TEXT_METADATA="/path/to/WebHound/assets/ml/text_secret_classifier/export_metadata.json"
EOF
    fi

    if [[ -n "${text_tokenizer}" ]]; then
        cat >>"$out" <<EOF
export WEBHOUND_TEXT_TOKENIZER="${text_tokenizer}"
EOF
    else
        cat >>"$out" <<'EOF'
# export WEBHOUND_TEXT_TOKENIZER="/path/to/WebHound/assets/ml/text_secret_classifier/tokenizer/tokenizer.json"
EOF
    fi

    echo "Создан: $out"
    echo "   WEBHOUND_ROOT=$repo_abs"
    echo "   ORT_DYLIB_PATH=$lib_abs"
    echo "   LD_LIBRARY_PATH добавит: $lib_dir_abs"

    if [[ -n "${vision_model}" ]]; then
        echo "   WEBHOUND_VISION_MODEL=$vision_model"
    else
        echo "   WEBHOUND_VISION_MODEL=NOT FOUND"
    fi

    if [[ -n "${text_model_dir}" ]]; then
        echo "   WEBHOUND_TEXT_MODEL_DIR=$text_model_dir"
    else
        echo "   WEBHOUND_TEXT_MODEL_DIR=NOT FOUND"
    fi

    if [[ -n "${text_model}" ]]; then
        echo "   WEBHOUND_TEXT_MODEL=$text_model"
    else
        echo "   WEBHOUND_TEXT_MODEL=NOT FOUND"
    fi

    if [[ -n "${text_metadata}" ]]; then
        echo "   WEBHOUND_TEXT_METADATA=$text_metadata"
    else
        echo "   WEBHOUND_TEXT_METADATA=NOT FOUND"
    fi

    if [[ -n "${text_tokenizer}" ]]; then
        echo "   WEBHOUND_TEXT_TOKENIZER=$text_tokenizer"
    else
        echo "   WEBHOUND_TEXT_TOKENIZER=NOT FOUND"
    fi

    echo ""
    echo "Использование:"
    echo "  source \"$out\""
    echo ""
    echo "Примеры:"
    echo "  WebHound images ./example.com/screenshots --model \"\$WEBHOUND_VISION_MODEL\""
    echo "  WebHound text-analyze ./example.com/sensitive_info.post.jsonl --model-dir \"\$WEBHOUND_TEXT_MODEL_DIR\""
    echo "  WebHound scan example.com --text-analyze --text-model-dir \"\$WEBHOUND_TEXT_MODEL_DIR\""
}

main "$@"
